#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = []
# ///

# Auto-generated by build.py - Do not edit directly
# Edit source files in src/ and run build.py to regenerate

# === reader.py ===
"""File reader module for parsing routing claim data."""

from dataclasses import dataclass
from typing import Generator


@dataclass(frozen=True, slots=True)
class ClaimRecord:
    """Represents a single routing claim record."""

    source: str
    dest: str
    claim_id: str
    status: str


def stream_lines(file_path: str) -> Generator[ClaimRecord, None, None]:
    """
    Stream and parse lines from a routing claims file.

    Yields parsed ClaimRecord tuples for each valid line in the file.
    Handles UTF-8 encoding and strips whitespace from each line.

    Args:
        file_path: Path to the input file containing routing claims.

    Yields:
        ClaimRecord: Parsed record with (source, dest, claim_id, status).
    """
    with open(file_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            parts = line.split("|")
            if len(parts) >= 4:
                yield ClaimRecord(
                    source=parts[0],
                    dest=parts[1],
                    claim_id=parts[2],
                    status=parts[3],
                )



if __name__ == "__main__":
    pass  # TODO: Implement main entry point
